# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bmi.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bmi.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tbmi.proto\x12\x03\x62mi\"H\n\x0bUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06weight\x18\x02 \x01(\x01\x12\x0e\n\x06height\x18\x03 \x01(\x01\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\",\n\nBMIRequest\x12\x0e\n\x06weight\x18\x01 \x01(\x01\x12\x0e\n\x06height\x18\x02 \x01(\x01\"\x1a\n\x0b\x42MIResponse\x12\x0b\n\x03\x62mi\x18\x01 \x01(\x01\"\x1e\n\x0f\x43lassifyRequest\x12\x0b\n\x03\x62mi\x18\x01 \x01(\x01\"$\n\x10\x43lassifyResponse\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\"6\n\x15RecommendationRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"0\n\x16RecommendationResponse\x12\x16\n\x0erecommendation\x18\x01 \x01(\t\"\x7f\n\x0b\x46inalResult\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06weight\x18\x02 \x01(\x01\x12\x0e\n\x06height\x18\x03 \x01(\x01\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\x12\x0b\n\x03\x62mi\x18\x05 \x01(\x01\x12\x10\n\x08\x63\x61tegory\x18\x06 \x01(\t\x12\x16\n\x0erecommendation\x18\x07 \x01(\t2B\n\x0eServerAService\x12\x30\n\nSubmitUser\x12\x10.bmi.UserRequest\x1a\x10.bmi.FinalResult2?\n\nBMIService\x12\x31\n\x0c\x43\x61lculateBMI\x12\x0f.bmi.BMIRequest\x1a\x10.bmi.BMIResponse2M\n\x0f\x43\x61tegoryService\x12:\n\x0b\x43lassifyBMI\x12\x14.bmi.ClassifyRequest\x1a\x15.bmi.ClassifyResponse2e\n\x15RecommendationService\x12L\n\x11GetRecommendation\x12\x1a.bmi.RecommendationRequest\x1a\x1b.bmi.RecommendationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bmi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUEST']._serialized_start=18
  _globals['_USERREQUEST']._serialized_end=90
  _globals['_BMIREQUEST']._serialized_start=92
  _globals['_BMIREQUEST']._serialized_end=136
  _globals['_BMIRESPONSE']._serialized_start=138
  _globals['_BMIRESPONSE']._serialized_end=164
  _globals['_CLASSIFYREQUEST']._serialized_start=166
  _globals['_CLASSIFYREQUEST']._serialized_end=196
  _globals['_CLASSIFYRESPONSE']._serialized_start=198
  _globals['_CLASSIFYRESPONSE']._serialized_end=234
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=236
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=290
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=292
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=340
  _globals['_FINALRESULT']._serialized_start=342
  _globals['_FINALRESULT']._serialized_end=469
  _globals['_SERVERASERVICE']._serialized_start=471
  _globals['_SERVERASERVICE']._serialized_end=537
  _globals['_BMISERVICE']._serialized_start=539
  _globals['_BMISERVICE']._serialized_end=602
  _globals['_CATEGORYSERVICE']._serialized_start=604
  _globals['_CATEGORYSERVICE']._serialized_end=681
  _globals['_RECOMMENDATIONSERVICE']._serialized_start=683
  _globals['_RECOMMENDATIONSERVICE']._serialized_end=784
# @@protoc_insertion_point(module_scope)
