# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import bmi_pb2 as bmi__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bmi_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServerAServiceStub(object):
    """========== Services ==========
    Client calls A
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitUser = channel.unary_unary(
                '/bmi.ServerAService/SubmitUser',
                request_serializer=bmi__pb2.UserRequest.SerializeToString,
                response_deserializer=bmi__pb2.FinalResult.FromString,
                _registered_method=True)


class ServerAServiceServicer(object):
    """========== Services ==========
    Client calls A
    """

    def SubmitUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerAServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitUser': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitUser,
                    request_deserializer=bmi__pb2.UserRequest.FromString,
                    response_serializer=bmi__pb2.FinalResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bmi.ServerAService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bmi.ServerAService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServerAService(object):
    """========== Services ==========
    Client calls A
    """

    @staticmethod
    def SubmitUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bmi.ServerAService/SubmitUser',
            bmi__pb2.UserRequest.SerializeToString,
            bmi__pb2.FinalResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BMIServiceStub(object):
    """A -> B
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateBMI = channel.unary_unary(
                '/bmi.BMIService/CalculateBMI',
                request_serializer=bmi__pb2.BMIRequest.SerializeToString,
                response_deserializer=bmi__pb2.BMIResponse.FromString,
                _registered_method=True)


class BMIServiceServicer(object):
    """A -> B
    """

    def CalculateBMI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BMIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateBMI': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateBMI,
                    request_deserializer=bmi__pb2.BMIRequest.FromString,
                    response_serializer=bmi__pb2.BMIResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bmi.BMIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bmi.BMIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BMIService(object):
    """A -> B
    """

    @staticmethod
    def CalculateBMI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bmi.BMIService/CalculateBMI',
            bmi__pb2.BMIRequest.SerializeToString,
            bmi__pb2.BMIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CategoryServiceStub(object):
    """B -> C
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClassifyBMI = channel.unary_unary(
                '/bmi.CategoryService/ClassifyBMI',
                request_serializer=bmi__pb2.ClassifyRequest.SerializeToString,
                response_deserializer=bmi__pb2.ClassifyResponse.FromString,
                _registered_method=True)


class CategoryServiceServicer(object):
    """B -> C
    """

    def ClassifyBMI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CategoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClassifyBMI': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyBMI,
                    request_deserializer=bmi__pb2.ClassifyRequest.FromString,
                    response_serializer=bmi__pb2.ClassifyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bmi.CategoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bmi.CategoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CategoryService(object):
    """B -> C
    """

    @staticmethod
    def ClassifyBMI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bmi.CategoryService/ClassifyBMI',
            bmi__pb2.ClassifyRequest.SerializeToString,
            bmi__pb2.ClassifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RecommendationServiceStub(object):
    """C -> D (then A stores & returns to client)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRecommendation = channel.unary_unary(
                '/bmi.RecommendationService/GetRecommendation',
                request_serializer=bmi__pb2.RecommendationRequest.SerializeToString,
                response_deserializer=bmi__pb2.RecommendationResponse.FromString,
                _registered_method=True)


class RecommendationServiceServicer(object):
    """C -> D (then A stores & returns to client)
    """

    def GetRecommendation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRecommendation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendation,
                    request_deserializer=bmi__pb2.RecommendationRequest.FromString,
                    response_serializer=bmi__pb2.RecommendationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bmi.RecommendationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bmi.RecommendationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecommendationService(object):
    """C -> D (then A stores & returns to client)
    """

    @staticmethod
    def GetRecommendation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bmi.RecommendationService/GetRecommendation',
            bmi__pb2.RecommendationRequest.SerializeToString,
            bmi__pb2.RecommendationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
